#!/bin/bash

release=$1

case "${release}" in
    ''|*[!0-9]*)
        is_number="false"
        ;;
    *)
        is_number="true"
        ;;
esac

if [ "${is_number}" = "false" ]; then
    echo "The release value may only be a number."
    exit 1
fi

old_release=$(bc -l <<< "${release}-1")

PRIMARY_ARCHES="armv7hl i686 x86_64 aarch64 ppc64le s390x"

KOJICLI=koji

"${KOJICLI}" clone-tag --all --latest-only "f${old_release}" "f${release}"
"${KOJICLI}" edit-tag -x mock.package_manager=dnf "f${release}"
"${KOJICLI}" add-tag "f${release}-container"
"${KOJICLI}" add-tag --parent "f${release}-container" --arches=x86_64 "f${release}-container-build"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-updates"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-compose"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-updates-candidate"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-updates-testing"
"${KOJICLI}" add-tag --parent "f${release}-updates-testing" "f${release}-updates-testing-pending"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-updates-pending"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-override"
"${KOJICLI}" add-tag --parent "f${release}-override" --arches="${PRIMARY_ARCHES}" "f${release}-build"
"${KOJICLI}" add-tag --parent "f${release}-updates-testing-pending" "f${release}-signing-pending"
"${KOJICLI}" add-tag --parent "f${release}-updates"  "f${release}-pending"
"${KOJICLI}" add-tag --parent "f${release}-build" --arches="${PRIMARY_ARCHES}" "f${release}-infra"
"${KOJICLI}" add-tag --parent "f${release}-infra" --arches="${PRIMARY_ARCHES}" "f${release}-infra-stg"
"${KOJICLI}" add-tag --parent "f${release}-infra-stg" "f${release}-infra-candidate"
"${KOJICLI}" add-tag --parent "f${release}-infra-stg" --arches="${PRIMARY_ARCHES}" "f${release}-infra-build"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-modularity"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-openh264"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-atomic"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-atomic-host-installer"
"${KOJICLI}" add-tag "f${release}-atomic-host-overrides"
"${KOJICLI}" edit-tag-inheritance "f${old_release}-updates-candidate" "f${old_release}-updates"
"${KOJICLI}" edit-tag-inheritance "f${old_release}-updates-testing" "f${old_release}-updates"
"${KOJICLI}" edit-tag-inheritance "f${old_release}-updates-testing-pending" "f${old_release}-updates-testing"
"${KOJICLI}" edit-tag-inheritance "f${old_release}-updates-pending" "f${old_release}-updates"
"${KOJICLI}" edit-tag-inheritance "f${old_release}-override" "f${old_release}-updates"
"${KOJICLI}" edit-tag -x mock.new_chroot=0  "f${release}"
"${KOJICLI}" edit-tag -x tag2distrepo.enabled=true -x tag2distrepo.keys=47dd8ef9  "f${release}-infra"
"${KOJICLI}" edit-tag -x tag2distrepo.enabled=true -x tag2distrepo.keys=47dd8ef9  "f${release}-infra-stg"
"${KOJICLI}" edit-tag --perm=admin "f${release}-build"
"${KOJICLI}" edit-tag --perm=fedora-override "f${release}-override"
"${KOJICLI}" edit-tag --perm=admin "f${release}-updates"
"${KOJICLI}" edit-tag --perm=admin "f${release}-updates-testing"
"${KOJICLI}" edit-tag --perm=autosign "f${release}-updates-testing-pending"
"${KOJICLI}" edit-tag --perm=admin "f${release}-updates-pending"
"${KOJICLI}" edit-tag --perm=admin "f${release}-atomic"
"${KOJICLI}" edit-tag --perm=autosign "f${release}-signing-pending"
"${KOJICLI}" edit-tag --perm=infra "f${release}-infra"
"${KOJICLI}" edit-tag --perm=infra "f${release}-infra-build"
"${KOJICLI}" edit-tag --perm=infra "f${release}-infra-stg"
"${KOJICLI}" edit-tag --perm=infra "f${release}-infra-candidate"
"${KOJICLI}" edit-tag --perm=atomic "f${release}-atomic-host-installer"
"${KOJICLI}" edit-tag --perm=atomic "f${release}-atomic-host-overrides"

# FCOS continuous builds: https://pagure.io/releng/issue/8165
"${KOJICLI}" add-tag "f${release}-coreos-continuous" --arches="x86_64 aarch64 ppc64le s390x"
"${KOJICLI}" add-target "f${release}-coreos-continuous" "f${release}-build" "f${release}-coreos-continuous"
"${KOJICLI}" edit-tag -x tag2distrepo.enabled=true "f${release}-coreos-continuous"

# FCOS signing tags that feed the coreos-pool tag: https://pagure.io/releng/issue/8294
"${KOJICLI}" add-tag "f${release}-coreos-signing-pending" --parent coreos-pool

# Set up a corresponding set of tags for modules.
modular_release=${release}-modular
old_modular_release=${old_release}-modular
"${KOJICLI}" add-tag "f${modular_release}"
"${KOJICLI}" edit-tag -x mock.package_manager=dnf "f${modular_release}"
"${KOJICLI}" add-tag --parent "f${modular_release}" "f${modular_release}-updates"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates" "f${modular_release}-updates-candidate"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates" "f${modular_release}-updates-testing"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates-testing" "f${modular_release}-updates-testing-pending"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates" "f${modular_release}-updates-pending"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates" "f${modular_release}-override"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates-testing-pending" "f${modular_release}-signing-pending"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates"  "f${modular_release}-pending"
"${KOJICLI}" edit-tag --perm=fedora-override "f${modular_release}-override"
"${KOJICLI}" edit-tag --perm=admin "f${modular_release}-updates"
"${KOJICLI}" edit-tag --perm=admin "f${modular_release}-updates-testing"
"${KOJICLI}" edit-tag --perm=autosign "f${modular_release}-updates-testing-pending"
"${KOJICLI}" edit-tag --perm=admin "f${modular_release}-updates-pending"
"${KOJICLI}" edit-tag --perm=autosign "f${modular_release}-signing-pending"
"${KOJICLI}" edit-tag --perm=autosign "f${modular_release}"

"${KOJICLI}" add-tag --parent module-package-list "module-f${release}-build"
"${KOJICLI}" add-external-repo -t "module-f${release}-build" "f${release}-build" "https://kojipkgs.fedoraproject.org/repos/f${release}-build/latest/\$arch/"

"${KOJICLI}" tag-pkg "f${release}-build" "$(${KOJICLI} latest-build "f${old_release}-build" glibc64 glibc32 --quiet|sed -e "s| .*||g" )"

"${KOJICLI}" add-target "f${release}" "f${release}-build" "f${release}-updates-candidate"
"${KOJICLI}" add-target "f${release}-candidate" "f${release}-build" "f${release}-updates-candidate"
"${KOJICLI}" add-target "f${release}-infra" "f${release}-infra-build" "f${release}-infra-candidate"
"${KOJICLI}" add-target "f${release}-container-candidate" "f${release}-container-build" "f${release}-container"
"${KOJICLI}" edit-target rawhide --dest-tag="f${release}-updates-candidate" --build-tag="f${release}-build"
"${KOJICLI}" edit-target rawhide-container-candidate --dest-tag="f${release}-container" --build-tag="f${release}-container-build"
"${KOJICLI}" edit-target "f${old_release}" --dest-tag="f${old_release}-pending"
"${KOJICLI}" edit-target "f${old_release}-candidate" --dest-tag="f${old_release}-pending"


"${KOJICLI}" remove-tag-inheritance rawhide "f${old_release}"
"${KOJICLI}" add-tag-inheritance rawhide "f${release}"
