#!/bin/bash

release=$1

case "${release}" in
    ''|*[!0-9]*)
        is_number="false"
        ;;
    *)
        is_number="true"
        ;;
esac

if [ "${is_number}" = "false" ]; then
    echo "The release value may only be a number."
    exit 1
fi

old_release=$(bc -l <<< "${release}-1")

PRIMARY_ARCHES="i686 x86_64 aarch64 ppc64le s390x"
FLATPAK_ARCHES="i686 x86_64"

KOJICLI=koji

"${KOJICLI}" clone-tag --all --latest-only "f${old_release}" "f${release}"
"${KOJICLI}" edit-tag -x mock.package_manager=dnf "f${release}"
"${KOJICLI}" add-tag "f${release}-container"
"${KOJICLI}" add-tag --parent "f${release}-container" --arches="x86_64 aarch64" "f${release}-container-build"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-updates"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-compose"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-updates-candidate"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-updates-testing"
"${KOJICLI}" add-tag --parent "f${release}-updates-testing" "f${release}-updates-testing-pending"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-updates-pending"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-override"
"${KOJICLI}" add-tag --parent "f${release}-override" --arches="${PRIMARY_ARCHES}" "f${release}-build"
"${KOJICLI}" add-tag --parent "f${release}-updates-testing-pending" "f${release}-signing-pending"
"${KOJICLI}" add-tag --parent "f${release}-updates"  "f${release}-pending"
"${KOJICLI}" add-tag --parent "f${release}-build" --arches="${PRIMARY_ARCHES}" "f${release}-infra"
"${KOJICLI}" add-tag --parent "f${release}-infra" --arches="${PRIMARY_ARCHES}" "f${release}-infra-stg"
"${KOJICLI}" add-tag --parent "f${release}-infra-stg" "f${release}-infra-candidate"
"${KOJICLI}" add-tag --parent "f${release}-infra-stg" --arches="${PRIMARY_ARCHES}" "f${release}-infra-build"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-modularity"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-openh264"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-atomic"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-atomic-host-installer"
"${KOJICLI}" add-tag --parent "f${release}" "f${release}-iot"
"${KOJICLI}" add-tag "f${release}-atomic-host-overrides"
"${KOJICLI}" edit-tag -x tag2distrepo.enabled=true -x tag2distrepo.keys=47dd8ef9  "f${release}-infra"
"${KOJICLI}" edit-tag -x tag2distrepo.enabled=true -x tag2distrepo.keys=47dd8ef9  "f${release}-infra-stg"
"${KOJICLI}" edit-tag --perm=admin "f${release}-build"
"${KOJICLI}" edit-tag --perm=fedora-override "f${release}-override"
"${KOJICLI}" edit-tag --perm=admin "f${release}-updates"
"${KOJICLI}" edit-tag --perm=admin "f${release}-updates-testing"
"${KOJICLI}" edit-tag --perm=autosign "f${release}-updates-testing-pending"
"${KOJICLI}" edit-tag --perm=admin "f${release}-updates-pending"
"${KOJICLI}" edit-tag --perm=admin "f${release}-atomic"
"${KOJICLI}" edit-tag --perm=autosign "f${release}-signing-pending"
"${KOJICLI}" edit-tag --perm=infra "f${release}-infra"
"${KOJICLI}" edit-tag --perm=infra "f${release}-infra-build"
"${KOJICLI}" edit-tag --perm=infra "f${release}-infra-stg"
"${KOJICLI}" edit-tag --perm=infra "f${release}-infra-candidate"
"${KOJICLI}" edit-tag --perm=atomic "f${release}-atomic-host-installer"
"${KOJICLI}" edit-tag --perm=atomic "f${release}-atomic-host-overrides"

# FCOS continuous builds: https://pagure.io/releng/issue/8165
"${KOJICLI}" add-tag "f${release}-coreos-continuous" --arches="x86_64 aarch64 ppc64le s390x"
"${KOJICLI}" add-target "f${release}-coreos-continuous" "f${release}-build" "f${release}-coreos-continuous"
"${KOJICLI}" edit-tag -x tag2distrepo.enabled=true "f${release}-coreos-continuous"

# FCOS signing tags that feed the coreos-pool tag: https://pagure.io/releng/issue/8294
"${KOJICLI}" add-tag "f${release}-coreos-signing-pending" --parent coreos-pool

# Set up a corresponding set of tags for modules.
modular_release=${release}-modular
old_modular_release=${old_release}-modular
"${KOJICLI}" add-tag "f${modular_release}"
"${KOJICLI}" edit-tag -x mock.package_manager=dnf "f${modular_release}"
"${KOJICLI}" add-tag --parent "f${modular_release}" "f${modular_release}-updates"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates" "f${modular_release}-updates-candidate"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates" "f${modular_release}-updates-testing"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates-testing" "f${modular_release}-updates-testing-pending"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates" "f${modular_release}-updates-pending"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates" "f${modular_release}-override"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates-testing-pending" "f${modular_release}-signing-pending"
"${KOJICLI}" add-tag --parent "f${modular_release}-updates"  "f${modular_release}-pending"
"${KOJICLI}" edit-tag --perm=fedora-override "f${modular_release}-override"
"${KOJICLI}" edit-tag --perm=admin "f${modular_release}-updates"
"${KOJICLI}" edit-tag --perm=admin "f${modular_release}-updates-testing"
"${KOJICLI}" edit-tag --perm=autosign "f${modular_release}-updates-testing-pending"
"${KOJICLI}" edit-tag --perm=admin "f${modular_release}-updates-pending"
"${KOJICLI}" edit-tag --perm=autosign "f${modular_release}-signing-pending"
"${KOJICLI}" edit-tag --perm=autosign "f${modular_release}"

#To add pkgs from old_modular_release tag to modular_release tag
pkgs=$(koji list-pkgs --quiet --tag="f${old_modular_release}" | awk '{ print $1}')
koji add-pkg --owner=releng "f${modular_release}" $pkgs

"${KOJICLI}" add-tag --parent module-package-list "module-f${release}-build"
"${KOJICLI}" add-external-repo -t "module-f${release}-build" "f${release}-build" "https://kojipkgs.fedoraproject.org/repos/f${release}-build/latest/\$arch/"

"${KOJICLI}" tag-pkg "f${release}-build" "$(${KOJICLI} latest-build "f${old_release}-build" glibc64 glibc32 --quiet|sed -e "s| .*||g" )"

# Set up a corresponding set of tags for containers.
container_release=${release}-container
"${KOJICLI}" add-tag --parent "f${container_release}" "f${container_release}-updates"
"${KOJICLI}" add-tag --parent "f${container_release}-updates" "f${container_release}-updates-candidate"
"${KOJICLI}" add-tag --parent "f${container_release}-updates" "f${container_release}-updates-testing"
"${KOJICLI}" add-tag --parent "f${container_release}-updates-testing" "f${container_release}-updates-testing-pending"
"${KOJICLI}" add-tag --parent "f${container_release}-updates" "f${container_release}-updates-pending"
"${KOJICLI}" add-tag --parent "f${container_release}-updates" "f${container_release}-override"

"${KOJICLI}" add-target "f${release}" "f${release}-build" "f${release}-updates-candidate"
"${KOJICLI}" add-target "f${release}-candidate" "f${release}-build" "f${release}-updates-candidate"
"${KOJICLI}" add-target "f${release}-infra" "f${release}-infra-build" "f${release}-infra-candidate"
"${KOJICLI}" add-target "f${release}-container-candidate" "f${release}-container-build" "f${release}-container-updates-candidate"
"${KOJICLI}" edit-target rawhide --dest-tag="f${release}-updates-candidate" --build-tag="f${release}-build"
"${KOJICLI}" edit-target rawhide-container-candidate --dest-tag="f${release}-container-updates-candidate" --build-tag="f${release}-container-build"


"${KOJICLI}" remove-tag-inheritance rawhide "f${old_release}"
"${KOJICLI}" add-tag-inheritance rawhide "f${release}"

#### The pre-F39 tags structure for Flatpak containers, that needs to be created ####

# Set up a corresponding set of tags for flatpaks.
# They are only setup for branched release.
"${KOJICLI}" add-tag "f${release}-flatpak"
"${KOJICLI}" add-tag --parent "f${release}-flatpak" "f${release}-flatpak-updates"
"${KOJICLI}" add-tag --parent "f${release}-flatpak-updates" "f${release}-flatpak-updates-candidate"
"${KOJICLI}" add-tag --parent "f${release}-flatpak-updates" "f${release}-flatpak-updates-testing"
"${KOJICLI}" add-tag --parent "f${release}-flatpak-updates-testing" "f${release}-flatpak-updates-testing-pending"
"${KOJICLI}" add-tag --parent "f${release}-flatpak-updates" "f${release}-flatpak-updates-pending"
"${KOJICLI}" add-tag --parent "f${release}-flatpak-updates" "f${release}-flatpak-override"
# Add packages from the stable release
flatpak_pkgs=$(koji list-pkgs --quiet --tag="f${old_release}-flatpak" | awk '{ print $1}')
"${KOJICLI}" add-pkg --owner=releng "f${release}-flatpak" $flatpak_pkgs

#### Destination tags ####

# These inherit from f${old_release} so that pkglist information doesn't need to be individually
# maintained for them, but are --intransitive so that we can fine-tune things when
# creating build tags

# Packages that are rebuilt for inclusion in runtimes (perhaps with reduced dependencies)
"${KOJICLI}" add-tag "f${release}-flatpak-runtime"
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-runtime" "f${release}" --intransitive

# Packages that are rebuilt for inclusion in applications (with prefix=/app)
"${KOJICLI}" add-tag "f${release}-flatpak-app"
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-app" "f${release}" --intransitive
"${KOJICLI}" add-group-pkg "f${release}-flatpak-app" build flatpak-rpm-macros flatpak-runtime-config
"${KOJICLI}" add-group-pkg "f${release}-flatpak-app" srpm-build flatpak-rpm-macros

#### Build tags ####

# The repository that tools (flatpak-module-tools, flatpak, ostree, etc) are installed from
# when building a flatpak. This is also used as the build tag when building Flatpaks
"${KOJICLI}" add-tag "f${release}-flatpak-container-build" --parent="f${release}-build" --arches="${FLATPAK_ARCHES}"
"${KOJICLI}" add-group "f${release}-flatpak-container-build" flatpak-build
"${KOJICLI}" add-group-pkg "f${release}-flatpak-container-build" flatpak-build flatpak-module-tools dnf tar

# The repository for build dependencies when building runtime RPMs
"${KOJICLI}" add-tag "f${release}-flatpak-runtime-build" --arches="${FLATPAK_ARCHES}"
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-runtime-build" "f${release}-flatpak-runtime" --priority=0
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-runtime-build" "f${release}-build" --priority=10

# The repository for build dependencies when building application RPMs
"${KOJICLI}" add-tag "f${release}-flatpak-app-build" --arches="${FLATPAK_ARCHES}"
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-app-build" "f${release}-flatpak-app" --priority=0
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-app-build" "f${release}-flatpak-runtime" --priority=10
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-app-build" "f${release}-build" --priority=20

#### Tags defining repositories for container installation ####

# An override tag that we can tag packages that have not gone stable yet for runtime inclusion
"${KOJICLI}" add-tag "f${release}-flatpak-runtime-override" --parent=f${release}

# The repository for getting runtime packages from when creating a container
"${KOJICLI}" add-tag "f${release}-flatpak-runtime-packages" --arches="${FLATPAK_ARCHES}"
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-runtime-packages" "f${release}-flatpak-runtime" --priority=0
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-runtime-packages" "f${release}-flatpak-runtime-override" --priority=10

# The repository for getting application packages from when creating a container
"${KOJICLI}" add-tag "f${release}-flatpak-app-packages" --arches="${FLATPAK_ARCHES}"
"${KOJICLI}" add-tag-inheritance "f${release}-flatpak-app-packages" "f${release}-flatpak-app" --priority=0

#### Extra Data ####

# Add extra data to the Flatpak build tag pointing to a) the tag where to find runtimes
# b) the tag to take runtime packages from c) the tag to take applications from
"${KOJICLI}" edit_tag "f${release}-flatpak-container-build" \
    -x flatpak.runtime_tag="f${release}-flatpak-updates-candidate" \
    -x flatpak.runtime_package_tag="f${release}-flatpak-runtime-packages" \
    -x flatpak.app_package_tag="f${release}-flatpak-app-packages"

#### Targets ####

# Targets for building Flatpak containers, runtime RPMs, and application RPMs
"${KOJICLI}" add-target "f${release}-flatpak-candidate" "f${release}-flatpak-container-build" "f${release}-flatpak-updates-candidate"
"${KOJICLI}" add-target "f${release}-flatpak-runtime" "f${release}-flatpak-runtime-build" "f${release}-flatpak-runtime"
"${KOJICLI}" add-target "f${release}-flatpak-app" "f${release}-flatpak-app-build" "f${release}-flatpak-app"

# And two lovely targets just to make kojira rebuild the installation repositories
"${KOJICLI}" add-target "f${release}-flatpak-runtime-kojira" "f${release}-flatpak-runtime-packages" "f${release}-flatpak-app"
"${KOJICLI}" add-target "f${release}-flatpak-app-kojira" "f${release}-flatpak-app-packages" "f${release}-flatpak-app"


# Point eln to new rawhide release
"${KOJICLI}" remove-tag-inheritance eln "f${old_release}"
"${KOJICLI}" add-tag-inheritance eln "f${release}"
"${KOJICLI}" remove-tag-inheritance eln-build "f${old_release}-build"
"${KOJICLI}" add-tag-inheritance eln-build "f${release}-build" --priority 5
