#!/bin/bash

TARGET=f27-build
DATE=$(date  "+%Y%m%d-%H-%M")
COMPOSEDIR=/mnt/koji/compose/cd/

mkdir $COMPOSEDIR/logs/$DATE/

pushd $COMPOSEDIR >& /dev/null
rm -rf fedora-atomic
git clone -q https://pagure.io/fedora-atomic.git
pushd fedora-atomic >& /dev/null
sed -i -e 's|^mirrorlist.*$|baseurl=https://kojipkgs.fedoraproject.org/repos/rawhide/latest/$basearch/|g' fedora-rawhide.repo
popd >& /dev/null


for arch in x86_64 aarch64 armhfp ppc64le
do
   ARCHLOG=$COMPOSEDIR/logs/$DATE/$arch/
   mkdir $ARCHLOG
   compose-koji runroot --new-chroot --use-shell --task-id --channel-override=compose --package=pungi --package=ostree --package=rpm-ostree --mount=/mnt/koji/compose/cd/ --mount=/mnt/koji/atomic-cd/ $TARGET $arch "rm -f /var/lib/rpm/__db*; rm -rf /var/cache/yum/*; set -x; pungi-make-ostree tree --log-dir=$ARCHLOG --treefile=/mnt/koji/compose/cd/fedora-atomic/fedora-atomic-host.json --repo=/mnt/koji/atomic-cd/" >$ARCHLOG/koji-task.log
done

# keep only the last weeks worth of ostree commits
ostree prune --repo=/mnt/koji/atomic-cd/ --keep-younger-than="7 days ago" --refs-only > $COMPOSEDIR/logs/$DATE/ostree-prune.log

# keep a weeks worth of logs
find $COMPOSEDIR/logs/  -xdev -depth -maxdepth 2 -mtime +7  -exec rm -rf {} \;
