#!/usr/bin/python
#
# Copyright (C) 20111-2013 Red Hat Inc,
# SPDX-License-Identifier:    GPL-2.0+
#
# Authors: Bill Nottingham <notting@redhat.com>
#          Toshio Kuratomi <tkuratom@redhat.com>
from __future__ import print_function

import argparse
import sys

import pdc_client


def setup_args():
    usage = "\nget-critpath <branch>"
    parser = argparse.ArgumentParser(usage=usage)
    parser.add_argument('branch')
    return parser

def main():
    parser = setup_args()
    args = parser.parse_args()

    pdc = pdc_client.PDCClient('fedora', develop=True)

    endpoint = pdc['component-branches']
    kwargs = dict(name=args.branch, active=True)
    existing = pdc.get_paged(endpoint, **kwargs)
    try:
        next(existing)
    except StopIteration:
        print("%s not a valid branch." % args.branch, file=sys.stderr)
        sys.exit(1)

    critpath_packages = pdc.get_paged(endpoint, critical_path=True, **kwargs)

    # De-duplicate and print the list.
    seen = set()
    for package in critpath_packages:
        name = package['global_component']
        if name in seen:
            continue
        print(name)
        seen.add(name)

if __name__ == '__main__':
    main()
